jekyll:
    image: jekyll/jekyll:3
    command: jekyll serve --livereload
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
        - .:/srv/jekyll
        - ./.gem-cache/bundle:/usr/local/bundle
